### PR TITLE
DataFileSystem: new method 'GetFileString' to read files to strings

### PR DESCRIPTION
**Pull request by NickRimmer**
To make possible read JSON files as strings, I've added a new method to do it.

### Usage example:
I want read JSON string from data file to use it with **CuiHelper.FromJson(...)** method.
Cause now it looks like we have CuiHelper method to build UI from JSON specification, but we can't read this specification from local.

So, with this new method **GetFileString(...)** we can do it now like this:
```C#
private void Example()
{
    var filePath = $"{GetType().Name}/profile-menu.json";
    var data = Interface.Oxide.DataFileSystem.GetFileString(filePath);

    // now you can use this string as template for your UI, 
    // replace some placeholders and send it to CuiHelper.FromJson(...) method

    Puts(data);
}
```

### CODE REVIEW

**Comment by NickRimmer** [comment]
I know, we have **Interface.uMod.DataFileSystem.ReadObject<...>** method and we can read some object and serialize it back to string. It will be a bit redundantly but can be used.

Probably, in this case will be better to update CuiHelper class, to read JSON not only from a string, but from a file too.

**Comment by Calytic** [comment]
We appreciate your contribution..

It is definitely a good idea to provide a method to read and write text files without relying on serialization if it isn't necessary.  That would be more performant and conceptually simpler.

However, the DataFileSystem is being deprecated very soon because the underlying implementation has a number of serious issues.  We have devised new abstractions which break up what this system does into many different parts and as such are more flexible and asynchronous (by default).  Naturally, I'd be reticent to add more features to the big ball of mud, creating the need for yet another deprecation.

As such, I don't have a problem with this PR, it makes sense and is consistent with how Oxide works.  My only problem is adding more stuff to the code-base, and creating more dependencies on it, when it's alternative is maturing quickly and offers a far superior alternative to DataFileSystem as a whole.

Again, thanks for the contribution and we will consider it in this context.

**Comment by lukespragg** [comment]
As Calytic suggested though, it wouldn't really be wise to add this only to have it re-implemented and deprecated in uMod since the entire system has been replaced already.

Thanks for the contribution though!

**Comment by NickRimmer** [comment]
Thank you for your responses. I'm looking forward to updates ~_~

**Pull request closed without merging**
