### PR TITLE
Update Permission.cs

### PR DESCRIPTION
**Pull request by Khan8615**
Removed extra allocations for permission & group system checks. Now forcing all plugins to register the names as lowercase with output response.

If this patch is accepted I will personally submit patches to every single umod plugin that does not currently register names in lowercase already.

If you have any questions or concerns in regards to these changes please let me know so that I may have a chance to address them in full detail.

### CODE REVIEW

**Comment by lukespragg** [comment]
I see no reason why plugins should be forced to register permissions in a certain casing. Yes, it's good practice visually, but casing shouldn't matter internally. StringComparer should be used instead rather than breaking plugins and warning unnecessarily.

**Comment by Khan8615** [comment]
A. It would save a lot of performance considering just about every plugin calls multiple permissions constantly.
B. You already force it on plugin submissions for them to be passed on umod.
C. Trying to do it any other way would not be performant and you would have trouble handling it in ProtoBuff accordingly.
D. This would be a step forward for once towards a more performant permission system. So even if you don't do it in Oxide at least make it a thing in umod's release.

How do I know this? I've spent the last 12 hours attempting all other routes and this was the best end result for performance without rewriting parts of the system completely.

I understand change is hard for people but sometimes it's for the best either way tho, I won't push it any further.

**Comment by lukespragg** [comment]
Hi Khan, I appreciate the attempt, but copying the code from a branch that already has the same changes is unnecessary. If you have any other suggestions for improving that branch, feel free to let us know or open a PR with the suggestions.

**Comment by Calytic** [comment]
This is an interesting idea. I should point out that I made similar changes to uMod's FileAuthManager (what was the Permissions library). Instead of failing when non-lowercase input was entered, I simply lowered the input before it was stored (in every case).  I will take another look at this. I had some difficulty creating the dictionaries with the proper StringComparer for FileAuthManager (though all DatabaseAuthManager dictionaries do use StringComparer.InvariantCultureIgnoreCase)

```csharp
public bool CreateGroup(string group, string title, int rank, string parent = "")
{
    // Check if it already exists
    if (GroupExists(group) || string.IsNullOrEmpty(group))
    {
        return false;
    }

    // Create the data
    GroupData data = new GroupData { Title = title, Rank = rank, ParentGroup = parent };

    // Add the group
    _groupdata.Add(group.ToLower(), data);

    return true;
}
```

I had not considered optimizing the methods by eliminating the ToLower call on subsequent method calls, primarily for backwards compatibility.  I agree with WheteThunger that backwards compatibility is important. In order to minimize impact we have two options as far as I can tell..
1. As Khan has done here, spit out a warning when non-lowercased permissions are registered - thus informing the developer that the permission registration and all subsequent permissions checks must also be lowercase.
2. Leave the ToLower calls in every permission-related function, thus losing any performance benefit from removing them.

Though option 2 does maximize BC, I am partial the option 1 for the performance benefit. I think it's fair to say that 90+% of cases follow the documentation and there isn't a single public example in code or in documentation that indicates non-lower-case permissions. It is frustrating to leave potential optimizations on the table because of an unknown quantity of private plugins who may have used undocumented methods. Perhaps we can mitigate that in uMod somehow, for example having multiple AuthManager's with different behavior (one fast, one for maximum BC). Admittedly that will result in a lot of duplication to fix an issue we don't even know exists.

**Comment by Khan8615** [comment]
> Hi Khan, I appreciate the attempt, but copying the code from a branch that already has the same changes is unnecessary. If you have any other suggestions for improving that branch, feel free to let us know or open a PR with the suggestions. Also note that the branch is there for testing, not for immediate use, and subject to change.

Hey Wulf, I was simply trying to finish your changes and port them over the latest release build so that we could have had something that worked and still gained some kind of performance improvement with this month's force wipe. If you notice in the pull request you had missed a few instances where new creations of hash sets were not being created with the string comparison checks & when it loads the data I had concerns with it not ignoring the case culture so I had added some additional checks there as well 
```cs
            userdata = ProtoStorage.Load<Dictionary<string, UserData>>("oxide.users")?.ToDictionary(x => x.Key, x => x.Value,
                StringComparer.OrdinalIgnoreCase) ?? new Dictionary<string, UserData>(StringComparer.OrdinalIgnoreCase);
            groupdata = ProtoStorage.Load<Dictionary<string, GroupData>>("oxide.groups")?.ToDictionary(x => x.Key, x => x.Value,
                StringComparer.OrdinalIgnoreCase) ?? new Dictionary<string, GroupData>(StringComparer.OrdinalIgnoreCase);
```



So Calytic, the reason why we would use OrdinalIgnoreCase is that InvariantCultureIgnoreCase uses comparison rules based on English, but without any regional variations. However, if we force English into code then I suppose it wouldn't be much of a problem anyway.


> This is an interesting idea. I should point out that I made similar changes to uMod's `FileAuthManager` (what was the Permissions library). Instead of failing when non-lowercase input was entered, I simply lowered the input before it was stored (in every case). I will take another look at this but I am sure that `DatabaseAuthManager` and `FileAuthManager` dictionaries/hashsets use `StringComparer.InvariantCultureIgnoreCase`
> 
> ```cs
> public bool CreateGroup(string group, string title, int rank, string parent = "")
> {
>     // Check if it already exists
>     if (GroupExists(group) || string.IsNullOrEmpty(group))
>     {
>         return false;
>     }
> 
>     // Create the data
>     GroupData data = new GroupData { Title = title, Rank = rank, ParentGroup = parent };
> 
>     // Add the group
>     _groupdata.Add(group.ToLower(), data);
> 
>     return true;
> }
> ```
> 
> I had not considered optimizing the methods by eliminating the `ToLower` call on subsequent method calls, primarily for backwards compatibility. I agree with WheteThunger that backwards compatibility is important. In order to minimize impact we have two options as far as I can tell..
> 
>     1. As Khan has done here, spit out a warning when non-lowercased permissions are registered - thus informing the developer that the permission registration and all subsequent permissions checks must also be lowercase.
> 
>     2. Leave the `ToLower` calls in every permission-related function, thus losing any performance benefit from removing them.
> 
> 
> Though option 2 does maximize BC, I am partial the option 1 for the performance benefit. I think it's fair to say that 90+% of cases follow the documentation and there isn't a single public example in code or in documentation that indicates non-lower-case permissions. It is frustrating to leave potential optimizations on the table because of an unknown quantity of private plugins who may have used undocumented methods. Perhaps we can mitigate that in uMod somehow, for example having multiple `AuthManager`'s with different behavior (one fast, one for maximum BC). Admittedly that will result in a lot of duplication to fix an issue we don't even know exists.
> 
> In any case, I'll take a look at it today.

**Comment by Khan8615** [comment]
@Calytic 

My initial first pull request on here would be the ideal way if I am being honest. But to save face with backward compatibility I had to compromise with your team and try to finish wulfs changes which he has since informed me are subject to understandable change and I should have done a pull request on his instead of rushing out an update for high pop servers.

**Pull request closed without merging**
