### PR TITLE
Enable subscribe internal hooks

### PR DESCRIPTION
**Pull request by rostov114**
Enable feature subscribe/unsubscribe internal hooks for plugins.

### CODE REVIEW

**Comment by lukespragg** [comment]
These are intentionally excluded.

**Comment by rostov114** [comment]
@lukespragg Maybe it makes sense to enable for those who have disabled the sandbox?

**Comment by lukespragg** [comment]
It isn’t about sandboxing, internal hooks are just wrappers generally. The intended hook is called by internal hooks.

**Comment by rostov114** [comment]
In rare cases, you need to subscribe to such hooks. I have sandbox disabled. But I still can't subscribe to them.

**Comment by lukespragg** [comment]
Do you have an example? I don’t recall any hooks that do not call the actual hook intended.

**Comment by rostov114** [comment]
`IOnServerUsersSet` and `IOnServerUsersRemove` not hooked on add moderator or owner.
In extremely rare cases, it is necessary to override the behavior of the internal hook.

**Comment by lukespragg** [comment]
Exposing internal hooks isn’t the solution for this, the solution would be to generalize those internal hooks for purpose outside of the core.

**Comment by rostov114** [comment]
I correctly understood that in such cases it is more correct to suggest edits in RustHooks.cs?

**Comment by lukespragg** [comment]
Yes, in your case, this would be what would be done:

https://github.com/OxideMod/Oxide.Rust/commit/d24427223ce0906bc999cfd5880ffdde5bd018c4

**Pull request closed without merging**
